DROP DATABASE UnicaribePT;
Create database UnicaribePT;
USE UnicaribePT;
drop table project;

select * from Project;
CREATE TABLE Project(
	ID INT AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    ASESOR VARCHAR(50) NOT NULL,
    PROGRAM INT NOT NULL,
    PERIOD INT NOT NULL,
    AUTHOR1 VARCHAR(100) NOT NULL,
    AUTHOR2 VARCHAR(100),
    AUTHOR3 VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    DESCRIPTIONALL VARCHAR(100),
    DATE DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE TypeUser(
	ID INT AUTO_INCREMENT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    DATE DATE,
    NOTE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER(
	ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    TYPEUSER INT NOT NULL,
    DATE DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE Period(
	ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50) NOT NULL,    
    DATE DATE,
    PRIMARY KEY (ID)
);
CREATE TABLE Program(
	ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50) NOT NULL,    
    DATE DATE,
    PRIMARY KEY (ID)
);
COMMIT;
show databases;
use unicaribept;
show tables;

INSERT INTO CLIENTE (NOMBRE,APELLIDO,FECHA) VALUES('JESUS ENRIQUE','PEREZ GONGORA',	SYSDATE());
INSERT INTO Program (NAME,DATE) VALUES('Ingeniría en Telemática',sysdate());
INSERT INTO user (NAME,EMAIL, PASSWORD,TYPEUSER, DATE) VALUES('Jesús Perez', '120300036@ucaribe.edu.mx','admin','Ingeniría en Telemática',sysdate());
select * from project

